package com.brovada;

public enum WidgetType {
    GROUP, DATE_PICKER, SELECT, TEXT_FIELD, TEXT_AREA, YES_NO, RADIO, CHECKBOX, AUTOCOMPLETE, MAP,
    PHONE_NUMBER, POSTAL_CODE, CREDIT_CARD, PASSWORD, TIME, PANEL, LABEL, DURATION

}
