package com.brovada.document.config;

public enum ComponentType {
    GROUP, DATE_PICKER, DROP_DOWN, SELECT, TEXT_FIELD, TEXT_AREA, YES_NO, RADIO, CHECKBOX, AUTOCOMPLETE, MAP,
    PHONE_NUMBER, POSTAL_CODE, CREDIT_CARD, PASSWORD, TIME, PANEL, LABEL, DURATION

}
